### ISSUE TITLE
get_historical() issues with dplyr in vignette

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#110]
Perhaps related to https://github.com/ropensci/bomrang/issues/105?

``` r
adlmax <- get_historical(stationid = "023000", type = "max")
#> Error in get_historical(stationid = "023000", type = "max"): could not find function "get_historical"
adlmax
#> Error in eval(expr, envir, enclos): object 'adlmax' not found
adlmax %>% 
  select(station_number, year:day, max_temperature) %>% 
  filter(month == 10)
#> Error in adlmax %>% select(station_number, year:day, max_temperature) %>% : could not find function "%>%"
```

<sup>Created on 2020-01-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'm working on the `devel` branch right now.

**Comment by adamhsparks** [comment]
Wait, I just realised, I have unmerged commits from `master` after I typed I was working on `devel`. Let me check that first.

**Comment by adamhsparks** [comment]
Nope, still there after merging the `master` branch

**Comment by adamhsparks** [comment]
https://github.com/ropensci/bomrang/blob/f8618849dc69a2545035733081b3cdb7da7a2438/vignettes/bomrang.Rmd#L1709

**Comment by jonocarroll** [comment]
I'll try to see what's going on but the first example looks like failure to document/export. The issue with select may be the same (not exported correctly).

**Comment by adamhsparks** [comment]
I did find one of the `@param`s wasn't documented in there I think and fixed that in the release I sent to CRAN last night. Working on a much larger release with new functionality right now so no hurry.

I just had to fix some tests that were causing failures on CRAN servers and had to get it pushed to CRAN by yesterday.

**Comment by adamhsparks** [comment]
I've been looking at `select()` this AM. It's being exported as far as I can tell, it's in the NAMESPACE with all the other dplyr functions that are re-exported.

Still digging to see what I find.

**Comment by adamhsparks** [comment]
This does work though.

```r
adlmax %>% 
  bomrang::select(station_number, year:day, max_temperature)
```

**Comment by adamhsparks** [comment]
Fixed! Will push to `devel` shortly.

**Comment by adamhsparks** [comment]
Fixed in https://github.com/ropensci/bomrang/commit/77ddd3028f2243406db84448232aaeeb8372f14a

**Comment by jonocarroll** [comment]
Is it clear what the issue was? I don't see any changes specific to `select` in that commit.

**Comment by adamhsparks** [comment]
No, I'm not clear on what the issue was either. I'm with you. I didn't see any changes in NAMESPACE that fixed it, but it works now. Black magic?

**Comment by jonocarroll** [comment]
Then let's never question it again, lest it break out of spite. Good work.
