### ISSUE TITLE
Fix failing CRAN checks

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#116]
* `get_historical()` still fails CRAN checks where there is no Internet connectivity.

* File caching directories are failing on macOS and Solaris???

**Comment by adamhsparks** [comment]
`get_historical()` only gives an error message *AFTER* checking the server. I wasn't aware of this as the other bomrang functions should fail before any request is made, fail early, fail often. So I'd not included a `skip_on_cran()` in the error checking section of `get_historical()` tests.

This is fixed in https://github.com/ropensci/bomrang/commit/fa9c0462c85f701633537d8d533c8d2c0ac05746

**Comment by adamhsparks** [comment]
Issues with file caching should be fixed with this commit, https://github.com/ropensci/bomrang/commit/1a90dcd0ff93f302fb40b1238ff83b085e500618 where `tempdir()` is used for writing any files to avoid any issues with not having write access to ~/

**Comment by adamhsparks** [comment]
These should be fixed. It's passing local, R-builder and and rhub checks.

**Comment by jonocarroll** [comment]
Do you need that to be a flag?

https://github.com/ropensci/bomrang/blob/master/.github/workflows/main.yml#L52

```
sudo -E apt-get -yq --no-install-suggests ...
```

**Comment by jonocarroll** [comment]
Or if you want to be verbose, `--yes --quiet`.

**Comment by adamhsparks** [comment]
Good catch. But it's already been fixed in the devel branch.

https://github.com/ropensci/bomrang/blob/1a90dcd0ff93f302fb40b1238ff83b085e500618/.github/workflows/main.yml#L49
