### ISSUE TITLE
BOM rainfall station list empty, leading to get_historical error

### ISSUE THREAD

**Issue by rensa** [ropensci/bomrang#119]
```r
> get_historical(stationid = "023000", type = "max")
Error in x[i] : only 0's may be mixed with negative subscripts
```

Running `debug(.get_ncc)`, it looks like this is a problem with [lines 263-4 of `get_historical.R`](https://github.com/ropensci/bomrang/blob/77f14342188ea1e48362eb0bfdb3c60dd9510ab4/R/get_historical.R#L263): the [list of rainfall stations](http://www.bom.gov.au/climate/data/lists_by_element/alphaAUS_136.txt) published by the BOM is currently empty (I assume erroneously, because the temperature ones look fine), and because the resulting table parse attempt (starting line 230) ends up with less than 7 rows, line 264 crashes due to a subscripting error.

```
Bureau of Meteorology product IDCJMC0014.                                       Produced: 19 Aug 2020
Australian stations measuring rainfall

0 stations

(c) Copyright Commonwealth of Australia 2020, Bureau of Meteorology (ABN 92 637 533 532) 
Please note Copyright, Disclaimer and Privacy Notice, accessible at <http://www.bom.gov.au/other/copyright.shtml>
```

I daresay this will fix itself once things settle on the BOM's end, but I'll try to work on a PR to make the function more robust (particularly since this crash happens even if someone isn't looking for rainfall data) in the morning!

**Comment by rensa** [comment]
The rainfall station list for 20 August 2020 is also empty, so maybe this isn't going to dix itself 😔

**Comment by adamhsparks** [comment]
Are we sure it’s not just the drought? 🤷‍♀️
