### ISSUE TITLE
get_historical() backward compatibility is broken

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#123]
I forgot to include a backwards compatible function for `get_historical()` when I revamped the function names to make them more uniform across the package.

**Comment by adamhsparks** [comment]
Should be fixed in https://github.com/ropensci/bomrang/commit/bcd3f74a826a32ef67a19d1e69722907bed058cb.

It works for me locally now. @paulr-bv to please confirm by installing the latest from Master. Sorry about that, but good catch.  🙏

**Comment by paulr-bv** [comment]
Thanks. Installed from Master again and now working as expected. ☺
