### ISSUE TITLE
`get_historical` returns `Error: Must subset rows with a valid subscript vector.`

### ISSUE THREAD

**Issue by njtierney** [ropensci/bomrang#124]
👋 Hello!

Thanks for maintaining `bomrang` :)

I get this error when using `get_historical` - possibly related to #119 and #120 I think, I'll try the dev version and report back.
 

    library(bomrang)
    #> Registered S3 method overwritten by 'hoardr':
    #>   method           from
    #>   print.cache_info httr
    #> 
    #> Attaching package: 'bomrang'
    #> The following object is masked from 'package:stats':
    #> 
    #>     filter
    #> The following object is masked from 'package:graphics':
    #> 
    #>     plot
    #> The following object is masked from 'package:base':
    #> 
    #>     plot

    melb_stations <- 
    bomrang::sweep_for_stations(latlon = c(-37.800372,
                                           144.996162))

    melbourne_weather <- bomrang::get_historical(stationid = melb_stations$site[1],
                                                 type = "max")
    #> Error: Must subset rows with a valid subscript vector.
    #> x Negative and positive locations can't be mixed.
    #> ℹ Subscript `1:nrows` has a positive value at location 1.

<sup>Created on 2020-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
<details>
<summary>
Session info
</summary>

    devtools::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                       
    #>  version  R version 4.0.2 (2020-06-22)
    #>  os       macOS Mojave 10.14.6        
    #>  system   x86_64, darwin17.0          
    #>  ui       X11                         
    #>  language (EN)                        
    #>  collate  en_AU.UTF-8                 
    #>  ctype    en_AU.UTF-8                 
    #>  tz       Australia/Melbourne         
    #>  date     2020-09-07                  
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package     * version    date       lib source                             
    #>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                     
    #>  backports     1.1.9      2020-08-24 [1] CRAN (R 4.0.0)                     
    #>  bomrang     * 0.7.0      2020-01-20 [1] CRAN (R 4.0.0)                     
    #>  callr         3.4.3      2020-03-28 [1] CRAN (R 4.0.0)                     
    #>  cli           2.0.2      2020-02-28 [1] CRAN (R 4.0.0)                     
    #>  codetools     0.2-16     2018-12-24 [1] CRAN (R 4.0.2)                     
    #>  crayon        1.3.4      2017-09-16 [1] CRAN (R 4.0.0)                     
    #>  curl          4.3        2019-12-02 [1] CRAN (R 4.0.0)                     
    #>  data.table    1.13.0     2020-07-24 [1] CRAN (R 4.0.2)                     
    #>  desc          1.2.0      2018-05-01 [1] CRAN (R 4.0.0)                     
    #>  devtools      2.3.1      2020-07-21 [1] CRAN (R 4.0.0)                     
    #>  digest        0.6.25     2020-02-23 [1] CRAN (R 4.0.0)                     
    #>  dplyr         1.0.2      2020-08-18 [1] CRAN (R 4.0.0)                     
    #>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.0)                     
    #>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)                     
    #>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                     
    #>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                     
    #>  generics      0.0.2      2018-11-29 [1] CRAN (R 4.0.0)                     
    #>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                     
    #>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)                     
    #>  hms           0.5.3      2020-01-08 [1] CRAN (R 4.0.0)                     
    #>  hoardr        0.5.2      2018-12-02 [1] CRAN (R 4.0.0)                     
    #>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.1)                     
    #>  httr          1.4.2      2020-07-20 [1] CRAN (R 4.0.2)                     
    #>  knitr         1.29.4     2020-09-04 [1] Github (yihui/knitr@1465255)       
    #>  lattice       0.20-41    2020-04-02 [1] CRAN (R 4.0.2)                     
    #>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.0)                     
    #>  magrittr      1.5.0.9000 2020-08-27 [1] Github (tidyverse/magrittr@15f6f07)
    #>  memoise       1.1.0      2017-04-21 [1] CRAN (R 4.0.0)                     
    #>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.2)                     
    #>  pkgbuild      1.1.0      2020-07-13 [1] CRAN (R 4.0.2)                     
    #>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                     
    #>  pkgload       1.1.0      2020-05-29 [1] CRAN (R 4.0.0)                     
    #>  prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.0.0)                     
    #>  processx      3.4.4      2020-09-03 [1] CRAN (R 4.0.2)                     
    #>  ps            1.3.4      2020-08-11 [1] CRAN (R 4.0.2)                     
    #>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                     
    #>  R6            2.4.1      2019-11-12 [1] CRAN (R 4.0.0)                     
    #>  rappdirs      0.3.1      2016-03-28 [1] CRAN (R 4.0.0)                     
    #>  raster        3.3-13     2020-07-17 [1] CRAN (R 4.0.2)                     
    #>  Rcpp          1.0.5      2020-07-06 [1] CRAN (R 4.0.0)                     
    #>  readr         1.3.1      2018-12-21 [1] CRAN (R 4.0.0)                     
    #>  remotes       2.2.0      2020-07-21 [1] CRAN (R 4.0.2)                     
    #>  rlang         0.4.7      2020-07-09 [1] CRAN (R 4.0.0)                     
    #>  rmarkdown     2.3.3      2020-08-27 [1] Github (rstudio/rmarkdown@204aa41) 
    #>  rprojroot     1.3-2      2018-01-03 [1] CRAN (R 4.0.0)                     
    #>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                     
    #>  sp            1.4-2      2020-05-20 [1] CRAN (R 4.0.0)                     
    #>  stringi       1.4.6      2020-02-17 [1] CRAN (R 4.0.0)                     
    #>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                     
    #>  testthat      2.3.2      2020-03-02 [1] CRAN (R 4.0.0)                     
    #>  tibble        3.0.3      2020-07-10 [1] CRAN (R 4.0.2)                     
    #>  tidyselect    1.1.0      2020-05-11 [1] CRAN (R 4.0.0)                     
    #>  usethis       1.6.1      2020-04-29 [1] CRAN (R 4.0.0)                     
    #>  vctrs         0.3.4      2020-08-29 [1] CRAN (R 4.0.2)                     
    #>  withr         2.2.0      2020-04-20 [1] CRAN (R 4.0.0)                     
    #>  xfun          0.16       2020-07-24 [1] CRAN (R 4.0.2)                     
    #>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                     
    #> 
    #> [1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by adamhsparks** [comment]
It's been fixed. I just need to get it on CRAN. See, https://github.com/ropensci/bomrang/issues/120
