### ISSUE TITLE
Access to BOM weather grids?

### ISSUE THREAD

**Issue by mbacou** [ropensci/bomrang#126]
@adamhsparks and Team,
Does the package provide access to BOM's interpolated **weather grids** (described here http://www.bom.gov.au/climate/data-services/maps.shtml)? I believe these are the grids also available for download at e.g. :

Gridded daily rainfall:
http://www.bom.gov.au/web03/ncc/www/awap/rainfall/totals/daily/grid/0.05/history/nat/2021011320210113.grid.Z (?)

Thanks, --Mel.

**Comment by adamhsparks** [comment]
Hi @mbacou, right now, no, this is not a function in bomrang but we’d welcome a pull request if you wished to contribute.

**Comment by PaulMelloy** [comment]
Just to add, 
For the moment I believe BOM weather grids are a  paid service. Currently `bomrang` only retrieves what is freely available.
I would be interested to know if I am wrong
Cheers

**Comment by mbacou** [comment]
Thx. Access restrictions are a bit confusing indeed. I found links to download daily grids in ASCII format at http://www.bom.gov.au/jsp/awap/rain/index.jsp, so I assume this is public access. Would be a great addition to this package indeed. PR if/when I can!

**Comment by maelle** [comment]
From the README

> This package has been archived due to BOM's ongoing unwillingness to allow programmatic access to their data and actively blocking any attempts made using this package or other similar efforts.
