### ISSUE TITLE
Install the package in R-studio

### ISSUE THREAD

**Issue by fadeh2013** [ropensci/bomrang#143]
First of all, I would like to thank you for the amazing package. I tried to install it using the provided code at the homepage of the package, but it does not work. However, I installed the package using the following code: 

```r
remotes::install_github("ropensci/bomrang@main", build_vignettes = TRUE)
```
</details>

**Comment by adamhsparks** [comment]
@fadeh2013, what homepage are you referring to?

Our README instructions currently say:

> bomrang has been archived from CRAN for reasons beyond bomrang actually being broken. As such at this time I've declined to "fix" the package. It can still be installed using the following commands.

if (!require("remotes")) {
  install.packages("remotes", repos = "http://cran.rstudio.com/")
  library("remotes")
}

install_github("ropensci/bomrang", build_vignettes = TRUE)

**Comment by adamhsparks** [comment]
@fadeh2013, which homepage are you referring to?

Currently our README states:
>bomrang has been archived from CRAN for reasons beyond bomrang actually being broken. As such at this time I've declined to "fix" the package. It can still be installed using the following commands.
```r
if (!require("remotes")) {
  install.packages("remotes", repos = "http://cran.rstudio.com/")
  library("remotes")
}

install_github("ropensci/bomrang", build_vignettes = TRUE)
```

I've just confirmed that this code does work and installs _bomrang_ and any necessary dependencies.

**Comment by maelle** [comment]
From the README

> This package has been archived due to BOM's ongoing unwillingness to allow programmatic access to their data and actively blocking any attempts made using this package or other similar efforts.
