### ISSUE TITLE
column 'state' in stations_site_list isn't reliable

### ISSUE THREAD

**Issue by HughParsonage** [ropensci/bomrang#35]
Probably too difficult to fix (I'm guessing it originates from BoM), but for example all stations in Vanuatu have `state` = `VIC`.

**Comment by adamhsparks** [comment]
We can do a check for data validity and assign the proper state in our databases, see https://github.com/ropensci/GSODR/blob/master/data-raw/fetch_isd-history.md#check-data-for-inconsistencies for an example.

**Comment by adamhsparks** [comment]
This really became an issue when the latest stations list from BOM put the Alice Springs Airport in South Australia.

I've implemented checks now for the location of the lon/lat values and used the value returned from that.

However, this is time-consuming, ~1hr on a 2.5Ghz Core i7 MacBook Pro. It still needs to be put into the `update_station_locations()` with a warning in the documentation about the amount of time it will take. This will also require `sf` and `raster` to be added to the imports with the methods I've used. `rgdal` is already an Import, so the effect should be minimal.

**Comment by HughParsonage** [comment]
What's the bottleneck? At any rate, I think `sf` (and any package used only in the updater) would be best suited for `Suggests`.

**Comment by adamhsparks** [comment]
Bottleneck:

```r
bom_locations <- 
  st_intersection(Oz, points) %>% 
  st_set_geometry(NULL)
```

https://github.com/ropensci/bomrang/blob/master/R/update_station_locations.R is a function in the package, not just in `data-raw`. So `sf` should be in the Imports, because I'm using it in that (updated) function as well, no?

**Comment by HughParsonage** [comment]
Hmmm my ASGS package might be worth looking into. This runs in a few seconds. 

system.time(bom[, State := latlon2SA(lat, lon, to = "SA4", return = "v")])

Not possible just to use `ASGS` on CRAN though, it's a teeny bit too big (1 GB) -- even GitHub chokes. Could do a `lite` version that only has states though.

**Comment by HughParsonage** [comment]
> https://github.com/ropensci/bomrang/blob/master/R/update_station_locations.R is a function in the package, not just in data-raw. So sf should be in the Imports, because I'm using it in that (updated) function as well, no?

Nope! You can use elements from `Suggests:` but you just have to use `if (requireNamespace("sf", quietly = TRUE))` whenever you do that. In this case, it would be fine because you can without `sf` you'd still be able to run `update_station_locations`, you just wouldn't get the benefit of the validation of `state`. For example, `ggplot2` uses `mgcv` in suggests even though it's used in `geom_smooth()`.

**Comment by adamhsparks** [comment]
ah, nice one!!! Thanks.

**Comment by adamhsparks** [comment]
I shoulda paid more attention when reading, it's right there: http://r-pkgs.had.co.nz/description.html#dependencies

**Comment by HughParsonage** [comment]
BTW here's my list of states by true state

```
                                 name                                 SA4 state
 1:                 BINDA POST OFFICE                      Capital Region   NSW
 2:      MURRAY RIVER @ BOUNDARY BEND                              Murray   VIC
 3:                       GOONDIWINDI          New England and North West   QLD
 4:                            BARKLY                            Ballarat   VIC
 5:              SNOWY RIVER @ WILLIS                 Latrobe - Gippsland   NSW
 6:                 MOUNT COTTON WEST                     Brisbane - East   QLD
 7:        MUNGINDI TM (BARWON RIVER)             Darling Downs - Maranoa   NSW
 8: ADELAIDE (WEST TERRACE / NGAYIRDA        Adelaide - Central and Hills    SA
 9:                        AUSTRALIND                             Bunbury    WA
10:       LEARMONTH SOLAR OBSERVATORY Western Australia - Outback (South)   NSW
11:              BREAM CREEK (STROUD)                              Hobart   TAS
12:              KINGSTON (SOUTH LEA)                              Hobart   NSW
13:            DARWIN PROFILER 050MHZ                              Darwin    NT
14:             ALICE SPRINGS AIRPORT        Northern Territory - Outback    SA
15:                  AINSLIE TYSON ST        Australian Capital Territory   NSW
16:                          O'CONNOR        Australian Capital Territory   VIC
17:              COCOS ISLAND AIRPORT                   Other Territories    WA
18:               NORFOLK ISLAND AERO                   Other Territories   NSW
                      STE_NAME16
 1:              New South Wales
 2:              New South Wales
 3:              New South Wales
 4:                     Victoria
 5:                     Victoria
 6:                   Queensland
 7:                   Queensland
 8:              South Australia
 9:            Western Australia
10:            Western Australia
11:                     Tasmania
12:                     Tasmania
13:           Northern Territory
14:           Northern Territory
15: Australian Capital Territory
16: Australian Capital Territory
17:            Other Territories
18:            Other Territories
```

**Comment by mpadge** [comment]
Two comments, if i may:

1. The reason for apparently "wrong" states is historical control: Vanuatu is not part of any state of Aus, so defaults to HQ which is Melb, ergo Vic. Alice Springs I'm not sure about, but imagine an historical time absent anything in NT, yet with the airport, hence default to supervisory authority of SA.
2. Even just a `Suggests: sf` can be non-trivial, but help can be found in [this `sf`-dep test repo](https://github.com/diminutive/depsf), [my own equivalent](https://github.com/mpadge/sftest), or my [`osmdata` package](https://github.com/ropensci/osmdata), which also has a `Suggests: sf`.

Hope that helps

**Comment by adamhsparks** [comment]
Hi Mark, the Alice Springs is a recent change, see the current `stations_site_list` in the released version of `bomrang`. It caused an error during testing because the state was wrong.

**Comment by HughParsonage** [comment]
What's the current runtime? If it's still an hour, you should probably contact CRAN first before submitting.

**Comment by adamhsparks** [comment]
It's still ~1hr, but currently the tests don't run on CRAN so it still runs as fast as previous versions. I've checked it on win-builder with no issues. Unless you think that it's an issue that I need to alert CRAN to for users after installation?

I'm guessing it is a fringe case where a user would update the lists. But I'm still looking for a way to improve the efficiency, not having much luck at the moment.

**Comment by HughParsonage** [comment]
Hold on I’ll write a patch today.

**Comment by adamhsparks** [comment]
It's all good. Andy Teucher gave a suggestion in rOpenSci slack to use `sf::st_join()`, much faster since it doesn't do geometry and I don't need geometry. Takes a few minutes longer now to download, but nothing like it was taking. Wrapping up testing now, should have it fixed shortly.

**Comment by HughParsonage** [comment]
I've got a one-line solution that takes 3 s and only requires a light package. (Just need to wait for CRAN to accept `ASGS.foyer` -- though shouldn't be any problems.)

**Comment by adamhsparks** [comment]
OK, great! Let's leave it for the next update. I need to get this update out the door for `janitor` to be updated on CRAN and I've managed to get all the tests written and code changed around for this right now.

Plus I have other things that are waiting, so I need to stop fiddling with this for a while.

**Comment by HughParsonage** [comment]
OK I know you have better things to think about, but one of the state-mismatches is quite funny: `WA/SA border village`. Original says `WA`, but the longitude is 129.0019 and the border lies on the 129th meridian; however, the border as gazetted lies about 100m east of the 129th meridian due to a surveying error in the 1920s. Nonetheless, the station was actually (just) in SA.

**Comment by adamhsparks** [comment]
Since I've had some issues with the CRAN submission, I've just readied a new version using `ASGS.foyer` to check and tidyed up a few other items. Will resubmit to CRAN soon.

Thanks, @HughParsonage for this. Much faster and more efficient.
