### ISSUE TITLE
Need Mark's ORCID

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#55]
Mark,
I'll need your ORCID for the JOSS paper, and I've put them in the DESCRIPTION file as well and will include it there.

**Comment by mpadge** [comment]
Cool, thanks for making me part of it all! I'll get it to ya asap...

**Comment by mpadge** [comment]
http://orcid.org/0000-0003-2172-5265

**Comment by adamhsparks** [comment]
I forgot, we need you affiliation too, see

https://github.com/ropensci/bomrang/blob/master/inst/paper/paper.md

**Comment by adamhsparks** [comment]
Thanks @mpadge

**Comment by mpadge** [comment]
i'm on to #56 today ...
