### ISSUE TITLE
weather_bulletin detailed documentation

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#56]
Functions that prepare a tidy data frame of BoM data have appendices in the vignette that detail what the columns contain.

`get_weather_bulletin()` currently lacks this documentation and I'm not sure I'm qualified to add it, I can't find it documented on BoM's site.

@mpadge is this something you can address after your holidays?

**Comment by mpadge** [comment]
I'll get straight onto it after 18th Sept! I don't think there is public-facing documentation, but it all accords with World Met Organization standards, so I should be able to provide both docs as you've done for all other tables and some kind of formal references.
