### ISSUE TITLE
Travis-ci build fails

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#67]
This seems to be a Travis issue, not `bomrang`. Apparently there are issues with accessing ftp sites.

https://github.com/travis-ci/travis-ci/issues/9352

and

https://github.com/travis-ci/travis-ci/issues/9112

**Comment by adamhsparks** [comment]
https://github.com/travis-ci/travis-ci/issues/9391

**Comment by adamhsparks** [comment]
Closing with switch to CircleCI and removing Travis as the Linux CI.

**Comment by jonocarroll** [comment]
Ouch for Travis, but neat - I haven't used CircleCI before. Another tool in the toolbox is always useful.

**Comment by adamhsparks** [comment]
I'll admit, I could've set up a Docker on Travis, but I was tired of fiddling with Travis to get `bomrang` and `GSODR` to pass CI checks.

@noamross really helped out with the config file for `GSODR`. I've adapted it for `bomrang`.
