### ISSUE TITLE
Field names in get_historical() should contain "_" not "."

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#69]
For consistency with field names from other functions in `bomrang`, the field names in the returned `data.frame` from `get_historical()` should contain "_" not "." for spaces.

**Comment by adamhsparks** [comment]
Hugh and I did do a bit of work to standardise as best we could. However, we've mostly stuck close to/with the original names that BOM uses for the different products.

**Comment by jonocarroll** [comment]
Closed via https://github.com/ropensci/bomrang/commit/c6f7a3f2cdef890e83e7a94360047fbda3e33aa8 in devel.
