### ISSUE TITLE
Devel branch not passing R CMD checks

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#70]
Tests are failing locally for `get_historical()`.

```r
══ testthat results  ══════════════════════════════════════════
  OK: 117 SKIPPED: 0 FAILED: 5
  1. Failure: Query stationid = '023000', type = 'rain' returns data.frame w/ correct station and some data (@test-get_historical.R#22) 
  2. Failure: Query stationid = '023000', type = 'rain' returns data.frame w/ correct station and some data (@test-get_historical.R#23) 
  3. Failure: Query latlon = c(-34.9285, 138.6007), type = 'rain' returns data.frame w/ correct station and some data (@test-get_historical.R#30) 
  4. Failure: Query latlon = c(-34.9285, 138.6007), type = 'rain' returns data.frame w/ correct station and some data (@test-get_historical.R#31) 
  5. Failure: Zip file URL is correctly obtained (@test-get_historical.R#38) 
  
  Error: testthat unit tests failed
  Execution halted
```

Any ideas @jonocarroll?

**Comment by adamhsparks** [comment]
I did some poking around. It looks like it's related to https://github.com/ropensci/bomrang/issues/69

The field names in the tests need to be updated.

**Comment by jonocarroll** [comment]
The match test assumed that the `p_c` mystery variable (which necessitates the second lookup) was a per-station constant, but that appears to not be the case. I've updated the test to allow for a more general match (d447401514cfe977102b04afa44e39383c314720). This now passes all 20 `get_historical` tests locally, but I'm getting 9 failures and 3 warnings from `get_precis` tests. Another issue, perhaps.

**Comment by jonocarroll** [comment]
Still failing but looks to be 3.5.0-related and @HughParsonage is on the case.

For now... "works on my machine."

**Comment by adamhsparks** [comment]
Thanks. Works on my machine now too with no tests failing for `get_precis` tests either, using 3.5.0.
