### ISSUE TITLE
How to specify the file name and file path when using “get_historical”?

### ISSUE THREAD

**Issue by lzb5600** [ropensci/bomrang#73]
I check the Reference Manual but couldn't find how to set them.

**Comment by jonocarroll** [comment]
This functionality is not available, and possibly won't be -- CRAN has rules about where packages may write files and `tempdir()` is a safe place for that. You should be presented with the data file location should you wish to move the files yourself. The `.zip` file is deleted but the contents remain.

**Comment by lzb5600** [comment]
OK that's fine. Thank you for your prompt response!

**Comment by adamhsparks** [comment]
The other option, if you wanted to save the raw files, is that `hoardr` is used for file caching already in `bomrang`. We could use that, but I don't think it's worth it for these data. I'd just save the cleaned/formatted data from `get_historical()` and not worry about it.
