### ISSUE TITLE
Error when downloading data?

### ISSUE THREAD

**Issue by lzb5600** [ropensci/bomrang#75]
when I run the following code:

library("bomrang")
tmpweather <- get_historical( stationid = "066208", type = "min")

The error message occurred:
Error in .get_zip_url(stationid, obscode) : 
  Error in retrieving resource identifiers.

I can download some other data with other latlon/stationid, but for some of them this error occurred,

**Comment by jonocarroll** [comment]
Just checking - are you _sure_ that's the `stationid` you used? I get the error `"Station not recognised."` which is what I'd expect to happen if the station wasn't listed in `bomrang`'s internal database.

Could you perhaps post a [`reprex`](https://github.com/tidyverse/reprex) with `si=TRUE`?

**Comment by jonocarroll** [comment]
The internal database *was* updated recently, so it's possible that it's not fully aligned for `get_historical()`. I can't check until I update to `R 3.5`.

**Comment by lzb5600** [comment]
Thank you @jonocarroll . I have modified the description of this issue. This should work.

**Comment by jonocarroll** [comment]
If I visit the URL which should provide the intermediate data, I get

```
No data available
Unfortunately there are no data available for the site number you have entered. 
This may be because either the station number is invalid, or the station has not 
observed the type of data requested.
```
I can make this error visible to the user when detected.

Entering the stationid `066208` here: http://www.bom.gov.au/climate/data/ shows the same error. Do you have reason to think there should be data for this station?

**Comment by lzb5600** [comment]
@jonocarroll Thanks. Actually, I am trying to get the historical weather condition for a set of latlon. When I loop through some coordinates, this error appears. 
For example, when I try:

get_historical(latlon = c(-34.21248, 150.9994), type = "min")

following message shows:

![image](https://user-images.githubusercontent.com/26557719/40692297-4e6a26a2-63f4-11e8-87b7-41c933f36170.png)


I am new to R, forgive me that I don't know how to use "reprex".

**Comment by jonocarroll** [comment]
Thank you, that's helpful. The 'Closest station' logic is supposedly finding the stationid physically closest to those coordinates, returning Wattamolla. According to the BOM search itself, it turns out Wattamolla has several stations

068218
068190 
068161 (closed)

but it does not list 066208 at all.

Using the bureau's station finder with those coordinates it suggests many closed stations are close, and the nearest open station is 068024 Darkes Forest (Kintyre) NSW (~14km drive). Comparing to an actual map, Wattamolla Beach/Falls/etc... are a little further away (~25km drive).

None of the above stationids are recognised by `bomrang`.

In any case, I am starting to think this is an issue with `sweep_for_stations` and/or the known list of stations. @adamhsparks?

**Comment by lzb5600** [comment]
I think I figure out the reason. When I try:

get_historical(latlon = c(-34.21248,150.9994), type = "solar")

It works and fetch the solar exposure data of station "066208".  It seems that it just select the nearest weather station no matter what type of data we are requiring. This may result in the error.

**Comment by jonocarroll** [comment]
With that code I get

`Closest station: 068219 (WOLLONGONG (APPIN))`

**Comment by jonocarroll** [comment]
The search for nearest stations occurs regardless of which type is requested. We do not have a cache of which data are available at each station.

**Comment by lzb5600** [comment]
@jonocarroll  I have used  update_forecast_towns() and update_station_locations(). May be this is the reason why we get different closest stations.

**Comment by jonocarroll** [comment]
That would have something to do with it, thank you.

**Comment by lzb5600** [comment]
@jonocarroll if we firstly select the "Data about" column as we require in the BOM website, then the proper stations will be listed. Maybe by doing this we do not need to cache them?  Just ignore my comments if that is unviable.

**Comment by lzb5600** [comment]
@jonocarroll Thanks for your help.

**Comment by adamhsparks** [comment]
Closing this issue. Please feel free to reopen if you have further details about this issue.
