### ISSUE TITLE
forecast max and min temp columns are assigned incorrectly

### ISSUE THREAD

**Issue by brendo1001** [ropensci/bomrang#76]
BOM_forecast <- get_precis_forecast(state = "NSW") ## state level data
loc_forecast<- BOM_forecast[BOM_forecast$town == "Wagga Wagga",] ## town level data

Probably just a parsing issue?

**Comment by adamhsparks** [comment]
Thanks, @brendo1001, simple but embarrassing mistake on my part.

Fixed in commit ce1f98174cea399bf1b6b86a2eeaefe575bbf536
