### ISSUE TITLE
Windows 10 -- Downloading Historic Data Fails

### ISSUE THREAD

**Issue by ahaw021** [ropensci/bomrang#77]
I get the following issue on windows 10. 

zipped <- utils::unzip(tmp, exdir = dirname(tmp))
Warning message:
In utils::unzip(tmp, exdir = dirname(tmp)) : zip file is corrupt

I compared the two files and for some reason, the util downloading package seems to corrupt the files. 

I tried using curl_download instead

Is it possible to update the internal.r file to use curl rather than utils::file_download()

It seems that curl has better cross os performance. 

Code i am using

```
url = "http://www.bom.gov.au/jsp/ncc/cdio/weatherData/av?p_display_type=dailyZippedDataFile&p_stn_num=070351&p_c=-989897037&p_nccObsCode=123"
tmp <- tempfile(fileext = ".zip")
curl::curl_download(url, tmp)
zipped <- utils::unzip(tmp, exdir = dirname(tmp))
unlink(tmp)
datfile <- grep("Data.csv", zipped, value = TRUE)
message("Data saved as ", datfile)
dat <- utils::read.csv(datfile, header = TRUE)
dat
```

**Comment by jonocarroll** [comment]
I'll have a look. Thanks for the heads up. I tested on Linux but cross-OS success would be worth switching for.

**Comment by adamhsparks** [comment]
Interesting. I tested it on Windows7 and `download.file()` worked there.

Now I wish I hadn't just released an update yesterday.

**Comment by ahaw021** [comment]
I jumped to the newest version of R

utils 3.5.0 
R 3.5.0 
CURL 3.2

All the other functions work perfectly (i.e. building stations JSON etc).

**Comment by adamhsparks** [comment]
@ahaw021 and @jonocarroll,
It looks like somehow I accidentally reverted a fix I'd put into place for this very issue.

Using the `download.file` option `mode = "wb"` should fix it. I've put that back the code in the `devel` branch and will test it when I get to work later.

**Comment by ahaw021** [comment]
That fixed it :D 

![image](https://user-images.githubusercontent.com/26753809/41512623-6e647220-72cf-11e8-8cff-8ff3ff31f9e4.png)

**Comment by adamhsparks** [comment]
Great! I'm not sure but maybe I just tested it on a Windows machine and didn't incorporate the fix or if it reverted, but it will be in the next CRAN release.

Since Jono and I both are not Windows users, I've also set Appveyor to run all unit tests now. It caught this error and passed with this patch in place.
