### ISSUE TITLE
Gettting historical wind data

### ISSUE THREAD

**Issue by brendo1001** [ropensci/bomrang#78]
Any chance we can pull the historical wind speed data in get_historical()? Useful for ET0. For that matter ET0  historical data could be useful, but this can be estimated so not too important.

**Comment by jonocarroll** [comment]
Any chance you could point to a source on the BOM site? So far `get_historical()` grabs data available from this section but I could expand on it if wind data is served somewhere

![image](https://user-images.githubusercontent.com/9496865/42797846-54ec4e86-89d0-11e8-8ee0-5cf3b8bce393.png)

**Comment by jonocarroll** [comment]
It's not clear that data can be extracted nicely. It appears to be stored in monthly CSV files by location with human-readable site names for the filenames, e.g. `http://www.bom.gov.au/watl/eto/tables/sa/adelaide_(kent_town)/adelaide_(kent_town)-200901.csv`. Adelaide, for example, only goes back as far as 2009, whereas the rainfall data goes back into the 1830s.

It wouldn't be too hard to scrape the entire site's wind/ET0 history month-by-month and combine them, but this may be a little imposing on the server. @adamhsparks?

**Comment by adamhsparks** [comment]
If you need historical wind data, many of the BOM stations are in the GHCN data available through https://github.com/ropensci/rnoaa or GSOD data available through https://github.com/ropensci/GSODR. However, the data in GSOD only goes back to 1929. Maybe those are better avenues than scraping the BOM site for this package?

I could check to see if there is a way to align station IDs between _GSODR_ and _bomrang_, but it's far down the list of things to do right now.

**Comment by brendo1001** [comment]
Thanks guys for looking into this. Its not a biggi but thought i would enquiry. I will follow up the GSODR lead though.

**Comment by adamhsparks** [comment]
Closing this issue. Can reconsider in future if a better option than scraping the site can be found.
