### ISSUE TITLE
Get Latest Radar Images

### ISSUE THREAD

**Issue by deanmarchiori** [ropensci/bomrang#82]
We currently have `get_satellite_imagery()`  which gets BOM Satellite GeoTIFF Imagery.  

Do we think there is value in adding functionality to get [radar](http://www.bom.gov.au/australia/radar/index.shtml) imagery? It seems like a popular product and may assist users looking to include imagery into rmarkdown reports etc. 

The images are all exposed to the FTP and can be brought in via `raster` so should be a low impact change. 

If interested, let me know and I can submit a PR

**Comment by jonocarroll** [comment]
Ooh! Ooh! `(gg?)animate`d loop of recent radar observations (like the BOM page)... I'd love that!

**Comment by adamhsparks** [comment]
Ooohhh, nice.

Yes, let's add this!

**Comment by deanmarchiori** [comment]
Have submitted PR #83 for review. Let me know what you think, open to any feedback.

**Comment by deanmarchiori** [comment]
PR #83 merged. Closing.
