### ISSUE TITLE
Incorporate static images in vignette

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#88]
The automated checks fail as will installation on users' systems if BOM fails to respond with an image.

Suggest incorporating static images into package vignette to avoid errors and make installation faster.

https://cran.r-project.org/web/checks/check_results_bomrang.html

**Comment by jonocarroll** [comment]
Functions which rely on other servers should probably be robust against
incidental failure. A common technique would be retry on fail. As for how
to test a function which may fail, I'd like to avoid the popular route of
'just don't test'. With proper error-handling the function could return
something of the appropriate class, even if it's empty.

**Comment by adamhsparks** [comment]
Good point. I've done this where numeric and text data are concerned, but haven't yet with images. Though that seems like a separate issue to me that should be opened as I'd still like the proper image to appear in the vignette.

**Comment by jonocarroll** [comment]
My issue with static is that it can become stale - either you or BOM change
something and all of a sudden the vignette renders but is wrong. Same
reason the code is in .Rmd not just .md but as a first-pass mitigation
strategy it would work.

**Comment by adamhsparks** [comment]
OK, I'll agree with that point but what you you put in documentation if BOM doesn't respond at the time the vignette is built?

**Comment by jonocarroll** [comment]
Depends how much code you want to write, but that's one option. Another
would be to logic-branch the output (possibly with a formal class). Or just
catch the error, print it as a message, and return safely from there. If
there's no processing of the file downstream from the image that works. If
there is, then _that_ needs to know what do do too.

I could imagine some sort of image_or_error class which could be checked
during test (being specific about the error).

**Comment by adamhsparks** [comment]
Nice. Thanks these ideas. I'll see what I can do.

**Comment by adamhsparks** [comment]
I've not coded anything yet but the .svg and this .png file are now in the devel branch of the repository.

https://github.com/ropensci/bomrang/blob/4ac4345e8ba1c2b533110b1f7aabccdebd0555f0/man/figures/image_error_message.png

**Comment by adamhsparks** [comment]
I did eventually use a `tryCatch()` in the functions to point to this error message if the proper file is not downloaded. I just forgot to close this issue.
