### ISSUE TITLE
Incorporate custom print method for historical metadata

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/bomrang#90]
Use custom S3 class and print method for `get_historical()` outputs to display the metadata above the data frame rather than returning a list.

**Comment by adamhsparks** [comment]
e.g., this commit https://github.com/adamhsparks/nasapower/commit/018ec29e90adcfb5dc52e0733f7a26736324180d

**Comment by adamhsparks** [comment]
All yours, mate. I'll be happy to see what you implement that I can borrow for `nasapower`.

**Comment by adamhsparks** [comment]
This shows where I ended up with the `nasapower` package for the metadata header.

https://adamhsparks.github.io/nasapower/articles/nasapower.html#using-get_power

**Comment by adamhsparks** [comment]
@jonocarroll, how are you coming with this?

**Comment by jonocarroll** [comment]
It's coming along but not as fast as I had hoped. I now have the `dplyr`-interfaces all working and passing checks, I just need to generalise the method to make it more useful. I fly again tomorrow, so prepare for incoming changes.

**Comment by adamhsparks** [comment]
I've merged the PR with the devel branch and am working on getting this ready for release. There's several bugs that have crept in somehow (perhaps BOM has changed some of the XML?) over time, it's time to get this out the door.

**Comment by adamhsparks** [comment]
I've implemented your new print method, @jonocarroll, for the `get_current_weather()` function as well. Works nicely. Having some issues with the `dplyr` re exported `filter()` function, will open a new issue and close this one as I think we're there for this issue.

**Comment by jonocarroll** [comment]
Cool beans! Re-exporting `filter` caused me some headaches but I thought I had it working now. Make sure to do a clean build/document.

**Comment by adamhsparks** [comment]
Yup, I've regenerated documentation due to some other changes. No more raw output from current stations and an alias for `get_current_weather()`, just `get_current()` to mirror `get_historical()`.
