### ISSUE TITLE
BoM water online

### ISSUE THREAD

**Issue by ghost** [ropensci/bomrang#96]
<details> <summary><strong>Session Info</strong></summary>

```r

```
</details>
BoM has an online portal to download water data, such as watercourse levels, storage volume, etc.
It would be very useful to be able to query water data by using a similar command as "get_historical" for climate records. Opposite to climate data, the water portal offers the possibility to download all the available records for a specific station since starting operating. Hence, it is possible to build datasets with long-term measurements to produce and analyse time series.
http://www.bom.gov.au/waterdata

**Comment by adamhsparks** [comment]
Thanks, Dario! We'll look into this.

**Comment by jmp75** [comment]
I noticed the package [bomWater](https://github.com/buzacott/bomWater). You should have a discussion to see whether a coordination is possible.

**Comment by maelle** [comment]
From the README

> This package has been archived due to BOM's ongoing unwillingness to allow programmatic access to their data and actively blocking any attempts made using this package or other similar efforts.
